package com.example.cards.model;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Cards extends BaseEntity{
	@GeneratedValue(strategy = GenerationType.AUTO)
	@GenericGenerator(name = "native",strategy = "native")
	@Id
	@Column(name = "card_id")
	@Schema(
			name = "cardId",
			description = "primaryKey AutoGenerated"
			)
	private long cardId;
	@Column(name="mobile_nmbr")
	@Schema(
			name = "customer mobile number",
			description = "mobile number of customer"
			)
	private String mobileNumber;
	@Column(name = "card_nmbr")
	@Schema(
			name = "card number",
			description = "12 digit card number"
			)
	private String cardNumber;
	@Column(name = "card_type")
	private String cardType;
	@Column(name = "total_limit")
	private int totalLimit;
	@Column(name = "amount_used")
	private int amountUsed;
	@Column(name = "available_amount")
	private int availableAmount;
	public long getCardId() {
		return cardId;
	}
	public void setCardId(long cardId) {
		this.cardId = cardId;
	}
	public String getMobileNumber() {
		return mobileNumber;
	}
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}
	public String getCardNumber() {
		return cardNumber;
	}
	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}
	public String getCardType() {
		return cardType;
	}
	public void setCardType(String cardType) {
		this.cardType = cardType;
	}
	public int getTotalLimit() {
		return totalLimit;
	}
	public void setTotalLimit(int totalLimit) {
		this.totalLimit = totalLimit;
	}
	public int getAmountUsed() {
		return amountUsed;
	}
	public void setAmountUsed(int amountUsed) {
		this.amountUsed = amountUsed;
	}
	public int getAvailableAmount() {
		return availableAmount;
	}
	public void setAvailableAmount(int availableAmount) {
		this.availableAmount = availableAmount;
	}
	@Override
	public String toString() {
		return "Cards [cardId=" + cardId + ", mobileNumber=" + mobileNumber + ", cardNumber=" + cardNumber
				+ ", cardType=" + cardType + ", totalLimit=" + totalLimit + ", amountUsed=" + amountUsed
				+ ", availableAmount=" + availableAmount + "]";
	}
	
}
