build:
 version: "2.0"
cards:
 message: "welcome to cards application web hook QA environment"
 contactDetails:
  name: "Nagaraju_qa"
  email: "cse_cards_qa@gmail.com"
 onSupportCAll:
  - (555)555-1234
  - (555)555-3456
   
