build:
 version: "3.0"
loans:
 message: "welcome to loans web hook dev environment"
 contactDetails:
  name: "Nagaraju"
  email: "cse_loans@gmail.com"
 onCallSupport: 
  - "(555)555-1234"
  - "(555)555-3456"

